databaseUri: 'jdbc:h2:./plugins/Aurora/aurora'
initialClaimBlocks: 1000
claimCreationTool: 'GOLDEN_SHOVEL'
claimInvestigationTool: 'STICK'
messages:
  tooFarAway: "§cThat's too far away!"
  notAClaim: "§cThere is no claim here."
  alreadyClaimed: "§cThere is already a claim here."
  blockClaimedBy: "§cThis block is claimed by %s."
  claimCornerSet: '§aFirst claim corner set.'
  needMoreClaimBlocks: '§cYou need %d more claim blocks to be able to claim this area.'
  wouldOverlapAnotherClaim: "§cYou can't create a claim here because it would overlap another one."
  claimCreated: "§aClaim created (%d x %d blocks)."
  claimResized: "§aClaim resized (%d x %d blocks)."
  resizingClaim: "§aResizing claim."
  noPermission: "§cYou don't have permission to do that here."
  raidPrevented: "§cA raid has been prevented."