databaseUri: 'jdbc:h2:./plugins/Aurora/aurora'
initialClaimBlocks: 1000
claimCreationTool: 'GOLDEN_SHOVEL'
claimInvestigationTool: 'STICK'
accrueClaimBlockEnabled: true
accrueClaimBlocksPerHour: 100
accrueClaimBlocksLimit: 10000
totalClaimsLimit: 10
messages:
  tooFarAway: "§cThat's too far away!"
  notAClaim: "§cThere is no claim here."
  alreadyClaimed: "§cThere is already a claim here."
  blockClaimedBy: "§cThis block is claimed by %s."
  claimCornerSet: '§aFirst claim corner set.'
  needMoreClaimBlocks: '§cYou need %d more claim blocks to be able to claim this area.'
  wouldOverlapAnotherClaim: "§cYou can't create a claim here because it would overlap another one."
  claimCreated: "§aClaim created (%d x %d blocks). You have %d claim blocks left."
  claimResized: "§aClaim resized (%d x %d blocks)."
  resizingClaim: "§aResizing claim."
  noPermission: "§cYou don't have permission to do that here."
  raidPrevented: "§cA raid has been prevented."
  pvpDisabled: "§cPvP is disabled in this claim."
  noClaimCreationPermission: "§cYou don't have permission to create claims."
  notClaimOwner: "§cYou cannot do this because you are not an owner of this claim."
  claimDeleted: "§aClaim deleted. You have %d claim blocks left."
  unknownPlayer: "§cI've never seen a player by that name."
  cannotSetOwnGroup: "§cYou can't change your own group."
  tooManyClaims: "§cYou can't create any more claims."

  claimListHeader: "These are your claims:"
  claimListEntry: "§2- %s at (%d, %d); %d blocks"
  claimListFooter: "You have used %d of your %d claim blocks. That means you have §a%d claim blocks remaining"
  claimListEmpty: "   You haven't created any claims yet."